[local]
localhost

[mongodb]
mongodb-dev.daws-92s.store

[catalogue]
catalogue-dev.daws-92s.store

[redis]
redis-dev.daws-92s.store

[user]
user-dev.daws-92s.store

[cart]
cart-dev.daws-92s.store
[mysql]
mysql-dev.daws-92s.store

[payment]
payment-dev.daws-92s.store

[rabbitmq]
rabbitmq-dev.daws-92s.store
[shipping]
shipping-dev.daws-92s.store
[frontend]
frontend-dev.daws-92s.store
